version: '3.2'

services:
  jupyterhub:
    build: jupyterhub
    image: jupyterhub_img
    container_name: jupyterhub
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: jupyterhub_data
        target: "/srv/jupyterhub"
      - type: bind
        source: ${DATA_VOLUME_CONTAINER}
        target: "/data"
        read_only: true
    environment:
      - DOCKER_NOTEBOOK_DIR=${DOCKER_NOTEBOOK_DIR}
      - DATA_VOLUME_CONTAINER=${DATA_VOLUME_CONTAINER}
      - DOCKER_JUPYTER_CONTAINER=jupyterlab_img
      - DOCKER_NETWORK_NAME=${COMPOSE_PROJECT_NAME}_default
      - HUB_IP=jupyterhub
      - HOST
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: on-failure

  jupyterlab:
    build: jupyterlab
    image: jupyterlab_img
    container_name: jupyterlab-build
    network_mode: none
    command: echo

volumes:
  jupyterhub_data:
