version: '3.2'

services:
  jupyterhub:
    build: ./docker/jupyterhub
    image: jupyterhub:1.1
    container_name: jupyterhub
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: jupyterhub_data
        target: "/srv/jupyterhub"
    environment:
      - DOCKER_NOTEBOOK_DIR=${DOCKER_NOTEBOOK_DIR}
      - DOCKER_NETWORK_NAME=jupyterhub_bdc-jupyter-net
      - HUB_IP=jupyterhub
      - DATA_SOURCE=${DATA_SOURCE}
      - DATA_TARGET=${DATA_TARGET}
      - EXAMPLES_SOURCE=${EXAMPLES_SOURCE}
      - EXAMPLES_TARGET=${EXAMPLES_TARGET}
      - HOST
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - bdc-jupyter-net

#  r-sits:
#    build: ./docker/r-sits
#    image: r-sits:1.0
#    container_name: jupyterlab_r-sits
#    networks:
#      - bdc-jupyter-net
#    command: echo

  odc:
    build: ./docker/odc/1.8
    image: odc:1.8
    container_name: jupyterlab_odc-1.8
    networks:
        - bdc-jupyter-net
    command: echo
#    volumes:
#      - type: bind
#        source: ${DATA_SOURCE}
#        target: ${DATA_TARGET}
#        read_only: true
#      - type: bind
#        source: ${EXAMPLES_SOURCE}
#        target: ${EXAMPLES_TARGET}
#        read_only: true
#    environment:
#      - DATA_SOURCE=${DATA_SOURCE}
#      - DATA_TARGET=${DATA_TARGET}
#      - EXAMPLES_SOURCE=${EXAMPLES_SOURCE}
#      - EXAMPLES_TARGET=${EXAMPLES_TARGET}

volumes:
  jupyterhub_data:

networks:
  bdc-jupyter-net:
